version: '3.8'

services:
  backend:
    build: ./backend
    hostname: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      back-tier:
        aliases:
          - backend

  frontend:
    build: ./frontend
    hostname: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    networks:
      back-tier:
          aliases:
            - frontend
      front-tier:
          aliases:
            - frontend
volumes:
  data:
  logs:

networks:
  back-tier:
  front-tier: